### PR TITLE
Add ts-fold, needed by tree-sitter+fold

### PR DESCRIPTION
**Pull request by thiagokokada**

### CODE REVIEW

**Comment by ckiee** [comment]
If you haven't changed it, won't `init.el` get regenerated next update?

**Comment by thiagokokada** [comment]
> If you haven't changed it, won't `init.el` get regenerated next update?

I don't think `init.el` is regenerated automatically ever. Even if you're running `doom install`, I think it only generates if you don't have this file already.

**Comment by ckiee** [comment]
[Are you sure?](https://github.com/nix-community/nix-doom-emacs/blob/master/.github/workflows/update_init_el.py)

**Comment by thiagokokada** [comment]
> [Are you sure?](https://github.com/nix-community/nix-doom-emacs/blob/master/.github/workflows/update_init_el.py)

Huh... Didn't know about this script.

Well, I think if this file ends up being reverted by default is fine, it shouldn't change anything except that it made my own testing easier.

Not sure if this script is working though. The `init.el` file seems to be kinda of out dated right now.

**Pull request merged**
